projects:
 mikro_next:
    schema: http://jhnnsrs-lab/mikro/schema
    documents: graphql/**/**.graphql
    extensions:
      turms:
        out_dir: mikro_next/api
        exclude_typenames: true
        dump_configuration: true
        dump_schema: true
        omited_document_rules:
          - "no_unused_fragments"
        freeze:
          enabled: true
        options:
          enabled: true
          use_enum_values: true
          allow_population_by_field_name: true
          extra: forbid
          types:
            - input
        stylers:
          - type: turms.stylers.default.DefaultStyler
          - type: turms.stylers.appender.AppenderStyler
            append_fragment: ""
        plugins:
          - type: turms.plugins.enums.EnumsPlugin
          - type: turms.plugins.inputs.InputsPlugin
          - type: turms.plugins.fragments.FragmentsPlugin
            object_bases:
              - mikro_next.traits.MikroFetchable
          - type: turms.plugins.operations.OperationsPlugin
          - type: turms.plugins.funcs.FuncsPlugin
            coercible_scalars:
              ArrayLike: mikro_next.scalars.ArrayCoercible
              ImageLike: mikro_next.scalars.ImageCoercible
              ImageFileLike: mikro_next.scalars.ImageFileCoercible
              FileLike: mikro_next.scalars.ImageFileCoercible
              MeshLike: mikro_next.scalars.MeshCoercible
              ParquetLike: mikro_next.scalars.ParquetCoercible
              ID: rath.scalars.IDCoercible
            coercible_inputs:
              AxisInput: str
            expand_input_types:
              - input
            global_kwargs:
              - type: mikro_next.rath.MikroNextRath
                key: rath
                description: The mikro rath client
            definitions:
              - type: subscription
                is_async: true
                use: mikro_next.funcs.asubscribe
              - type: query
                is_async: true
                use: mikro_next.funcs.aexecute
              - type: mutation
                is_async: true
                use: mikro_next.funcs.aexecute
              - type: subscription
                use: mikro_next.funcs.subscribe
              - type: query
                use: mikro_next.funcs.execute
              - type: mutation
                use: mikro_next.funcs.execute
        scalar_definitions:
          Any: typing.Any
          UUID: str
          StructureString: str
          ArrayLike: mikro_next.scalars.ArrayLike
          ImageLike: mikro_next.scalars.ImageLike
          LabelsLike: mikro_next.scalars.LabelsLike
          ParquetLike: mikro_next.scalars.ParquetLike
          FileLike: mikro_next.scalars.FileLike
          MeshLike: mikro_next.scalars.MeshLike
          ImageFileLike: mikro_next.scalars.ImageFileLike
          Upload: mikro_next.scalars.Upload
          Vector: mikro_next.scalars.Vector
          TwoDVector: mikro_next.scalars.TwoDVector
          ThreeDVector: mikro_next.scalars.ThreeDVector
          FourDVector: mikro_next.scalars.FourDVector
          FiveDVector: mikro_next.scalars.FiveDVector
          Matrix: mikro_next.scalars.Matrix
          GenericQuantity: kanne.scalars.GenericQuantity
          
          Metric: typing.Any
          MetricMap: typing.Any
          Duration: kanne.scalars.Duration
          Length: kanne.scalars.Length
          Unit: kanne.scalars.Unit
          Power: kanne.scalars.Power
          Frequency: kanne.scalars.Frequency
          Temperature: kanne.scalars.Temperature
          MikroStore: mikro_next.scalars.MikroStore
          FourByFourMatrix: mikro_next.scalars.FourByFourMatrix
          ID: rath.scalars.ID
          RGBAColor: mikro_next.scalars.RGBAColor
        additional_bases:
          AxisInput:
            - mikro_next.traits.AxisInputTrait
          ValueHistogramInput:
            - mikro_next.traits.ValueHistogramInputTrait
          CoordinateAnchorInput:
            - mikro_next.traits.CoordinateAnchorInputTrait
          Image:
            - mikro_next.traits.HasZarrStoreTrait
          Table:
            - mikro_next.traits.HasParquestStoreTrait
          ZarrStore:
            - mikro_next.traits.HasZarrStoreAccessor
          ParquetStore:
            - mikro_next.traits.HasParquetStoreAccesor
          BigFileStore:
            - mikro_next.traits.HasDownloadAccessor
          MediaStore:
            - mikro_next.traits.HasPresignedDownloadAccessor
          ROI:
            - mikro_next.traits.IsVectorizableTrait
          TransformationView:
            - mikro_next.traits.HasPixelSizeTrait
          Lens:
            - mikro_next.traits.Lensable
          ADataset:
            - mikro_next.traits.DatasetTrait
          Scene:
            - mikro_next.traits.SceneTrait
          CoordinateSystem:
            - mikro_next.traits.CoordinateSystemTrait
          ScaleTransformation:
            - mikro_next.traits.TransformationTrait
          TranslationTransformation:
            - mikro_next.traits.TransformationTrait
          AffineTransformation:
            - mikro_next.traits.TransformationTrait
          RotationTransformation:
            - mikro_next.traits.TransformationTrait
          IdentityTransformation:
            - mikro_next.traits.TransformationTrait
          MapAxisTransformation:
            - mikro_next.traits.TransformationTrait
          FieldTransformation:
            - mikro_next.traits.TransformationTrait
          SequenceTransformation:
            - mikro_next.traits.TransformationTrait
          ByDimensionTransformation:
            - mikro_next.traits.TransformationTrait
          BijectionTransformation:
            - mikro_next.traits.TransformationTrait
          UnmappableTransformation:
            - mikro_next.traits.TransformationTrait
          DataArray:
            - mikro_next.traits.DataArrayTrait
          CreateADatasetInput:
            - mikro_next.traits.CreateADatasetTrait
          File:
            - mikro_next.traits.FileTrait
