version: "3.4"

services:
  redis:
    image: redis:latest
  db:
    image: jhnnsrs/db:next
    restart: always
    environment:
      POSTGRES_MULTIPLE_DATABASES: mikro
      POSTGRES_PASSWORD: hello_django
      POSTGRES_USER: hello_django
  mikro:
    depends_on:
    - redis
    - db
    - minio
    image: jhnnsrs/mikro:next
    command: bash run-debug.sh
    ports:
    - 8456:80
    volumes:
    - ./configs/mikro_next.yaml:/workspace/config.yaml
    - ./public_key.pem:/workspace/public_key.pem
  minio:
    command: server /data
    environment:
      MINIO_ROOT_PASSWORD: minio_root
      MINIO_ROOT_USER: minio_root
    image: minio/minio:latest
    ports:
    - 8457:9000
  initc:
    depends_on:
      minio:
        condition: service_started
    environment:
      MINIO_HOST: http://minio:9000
      MINIO_ROOT_PASSWORD: minio_root
      MINIO_ROOT_USER: minio_root
    image: jhnnsrs/init:prod
    volumes:
    - ./configs/minio.yaml:/workspace/config.yaml


